os:
  - linux
  - osx

env:
  - TEST_SHELL=bash
  - TEST_SHELL=zsh

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == osx ]]; then
      brew install bats zsh
    else
      sudo add-apt-repository ppa:duggan/bats --yes
      sudo apt-get update -qq
      sudo apt-get install -qq -y bats zsh
    fi

script:
  - make test
